# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff47436c96842b1ab4a894c8f0af028ac13cc47959facd5b928087d57d1bd51db34e1339f49cf1e1e5f5ba741162d989c87b3a48ccc40a13e0dc72874621ec7

test:
  secret_key_base: 3b5c94fedfd606b998b36748bbfa92f13d9a4bb52d219b36b58ab99eaf3cfb7196b9650e46e1a1b58f399e6343cc9664d33dfccbbb5922df18fdce65bdd42de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
